// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace CarbonDatabase
{
	public class CarbonAsset : CarbonBaseObject {

		public override String AssemblyName { get {return "CarbonAsset";} }
		public Uri FilePath { get; set; }
		public String FileName { get; set; }
		public String Kind { get; set; }

	}
}

