// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CarbonDatabase {
	/*
		 * A character can have many attributes.
		 * Age, height, weight, description
		 * These can be defined by adding them via a list view 
		 * or similar. It makes no sense to define a finate amount of data
		 * for all characters.
		 * 
		 * However the constructor will add some common keys 
		 * to get started as this functions as a template object
		 */ 
	public class Character : Entity {

		public override String AssemblyName { get {return "Character";} }

		public Character() : base() {
			CarbonAttribute age = new CarbonAttribute("Age", 22);
			CarbonAttribute weight = new CarbonAttribute("Weight", "100 lbs");
			CarbonAttribute height = new CarbonAttribute("Height", "5' 10\"");
			CarbonAttribute description = new CarbonAttribute("Description", "");
			CarbonAttribute hairColor = new CarbonAttribute("Hair Color", "Brown");
			CarbonAttribute eyeColor = new CarbonAttribute("Eye Color", "Blue");
			// List ones
			CarbonAttribute motivators = new CarbonAttribute("Motivators", new List<String>());
			CarbonAttribute weaknesses = new CarbonAttribute("Weaknesses", new List<String>());
			CarbonAttribute fears = new CarbonAttribute("Fears", new List<String>());

			this.AddAttribute(age);
			this.AddAttribute(weight);
			this.AddAttribute(height);
			this.AddAttribute(description);
			this.AddAttribute(hairColor);
			this.AddAttribute(eyeColor);

			this.AddAttribute(motivators);
			this.AddAttribute(weaknesses);
			this.AddAttribute(fears);
		}
	}
}

