// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CarbonDatabase {
	public class Location : CarbonBaseObject {

		public override String AssemblyName { get {return "Location";} }
		public List<CarbonAttribute> LocationParts { get; set; }
		public List<CarbonAsset> Assets { get; set; }
		// TODO this could be a Vector4
		/*
		 * This contains 4 coordinates, this is for a location in space and time
		 */
		public double[] Coordinates = new double[4]{0,0,0,0};

		public List<Character> RelevantCharacters {get;set;}

	}
}

